### PR TITLE
Genres carousel added !!

### PR DESCRIPTION
**Pull request by AKACHI-4**
## Related Issue

Closes: #63 

## Description of Changes
Popular Genres Filter is added after the Trending section It is combined Genre card and each card direct user to the specific genres movie

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### Mobile View
image
<br>
### Normal web page view 
image

<br>

**_Kindly check it and suggest if further changes need to be made.
PS.: Sorry to generate PR this late I have my exams going on so....._**

### CODE REVIEW

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
It have some deployment issues as the code has been updated a lot! Kindly go through it once again and update it to the latest. @AKACHI-4

**Comment by AKACHI-4** [comment]
Okay lemme check it ...

**Comment by AKACHI-4** [comment]
Does it because of changes in package.json, package-lock.json and yarn.lock

**Comment by AKACHI-4** [comment]
I generated a new commit can you check it again whether it is okay now or not ?? To resolve deployment failed issue I changed the files package.json, package-lock.json and yarn.lock, I feel it because of yarn.lock. But If further change is required So I will review it again

**Comment by AKACHI-4** [comment]
Hey 👋 Is this pull request still creating problem ??

**Comment by sourabhsikarwar** [comment]
Please resolve conflicts @AKACHI-4

**Comment by AKACHI-4** [comment]
image
I don't have write access to resolve conflicts. What to do ?

**Comment by AKACHI-4** [comment]
I think I should raise a new PR for issue as it will be more cleaner with updated workflow

**Pull request closed without merging**
