### PR TITLE
fix: invisible sun, moon icon during theme toggle 👷🏻‍♂️⚒️ 

### LINKED ISSUE #544: [BUG]: theme toggle button not properly working 🙅🏻❌
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | The Bug is about the svg elements present in the theme toggle failing to change its color, So the svg icons not visible after toggling the theme |
| **Location of the bug** | Nav bar |
| **Expected behavior** | The  svg icons not to be affected during the theme toggle |

## Screenshots

https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/92252895/5bef0ee9-ae26-4d9e-9422-cdc45f2b2202

### PR DESCRIPTION
**Pull request by 0xabdulkhaliq**
## Description of Changes
- Fixed the invisible colors of icons inside theme toggle component during toggling theme.
- And made the Dark Theme as default by request of @sourabhsikarwar.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original [Toggling Dark Mode]      |       Updated  [Toggling Dark Mode]    |
| :-----------------: | :------------------: |
|image |image|

|Original [Page Starts with Light Mode]|Updated [Page Starts with Dark Mode]|
|:----:|:---:|
|image|image|

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@sourabhsikarwar your review is appreciated 🙌🏻

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Deployment failed

13:38:21.948 | Line 226:18:  'Splide' is not defined       react/jsx-no-undef
13:38:21.948 | Line 228:22:  'SplideSlide' is not defined  react/jsx-no-undef
13:38:21.948 | Line 229:24:  'Youtube' is not defined      react/jsx-no-undef

**Comment by 0xabdulkhalid** [comment]
@sourabhsikarwar I never touched those lines you mentioning now.

These errors are due to other people's PR merges, This PR is about modifying the Styling.

I think you want to revert the changes from any other merged PR.

**Comment by 0xabdulkhalid** [comment]
Now only i'm gone through this repository's PRs.

Many of them were not tested by deploying the Vercel Application.

You just merge them without testing ⚠️ 

So that now it's happening, I cannot do anything now.

Those conflicts are happen by any other previously merged PR's.

You can merge this PR, I can assure that this won't create any errors, Cuz I only handled the Styling.

Hope you understood.

**Comment by sourabhsikarwar** [comment]
Bro, I have check each and every PR on deployment also. You can take a push from master and then push it back. I'll try to deploy it. Many of the contributor gone through this issue because of old code.

**Pull request closed without merging**
