### PR TITLE
Scroll to top button bug and design update

### LINKED ISSUE #313: [BUG]: scroll to top button
- [ ] Would you like to take up this task? 
- [ ] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | scroll to top button hiding footer section content |
| **Location of the bug** | every page |
| **Expected behavior** | when we reach end of the page then  we  add some margin or bottom px to scroll to top button  |

## Screenshots (if any)
---
|     Screenshot 1 (if any)       |       Screenshot 2 (if any)     |
| :-----------------: | :------------------: |
| Screenshot 1 | Screenshot 2 |

Screenshot (142)

Please provide any necessary screenshots to illustrate.

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
## Related Issue
scroll to top button hiding footer section content
and size of the icon is to big

Closes: #313 

## Description of Changes
design 
when we reach end of the page then we add some bottom px 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       

Screenshot (151)
Screenshot (150)

Updated

Screenshot (152)

Screenshot (154)

### CODE REVIEW

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
It is failing in deployment, kindly take a pull and the update it @mandliyarajendra11

**Comment by mandliyarajendra11** [comment]
> It is failing in deployment, kindly take a pull and the update it @mandliyarajendra11

but i doest facing any issue 
it run property in localhost

**Comment by mandliyarajendra11** [comment]
> It is failing in deployment, kindly take a pull and the update it @mandliyarajendra11

one more thing some contributor opening issue related to about us page responsive 

but i already solved this issue ( check file change  )

**Comment by sourabhsikarwar** [comment]
Resolve conflicts @mandliyarajendra11

**Comment by mandliyarajendra11** [comment]
> Resolve conflicts @mandliyarajendra11

solved

**Pull request merged**
