### PR TITLE
circleRating & date added

### PR DESCRIPTION
**Pull request by BhartiNagpure**
#391  Rating and Date 

Closes: #391 

## Description of Changes
I am added new feature to handle the rating of movie in circularRating with color, based on average like red for below 5 rating orange for greater that 5 and green for below the 7 rating, and also  added date on movie card.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| | :------------------: |
| 
Screenshot 2023-07-10 114516
 |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by BhartiNagpure** [comment]
@sourabhsikarwar please review my PR .

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Please resolve conflicts @BhartiNagpure

**Comment by BhartiNagpure** [comment]
> Please resolve conflicts @BhartiNagpure

@sourabhsikarwar  Resolve conflict

**Comment by BhartiNagpure** [comment]
@sourabhsikarwar I am done with my work please review it.

**Comment by sourabhsikarwar** [comment]
Error in deployment

Failed to compile.
--
20:51:51.596 |  
20:51:51.597 | [eslint]
20:51:51.597 | src/components/Carousel/Trending.jsx
20:51:51.597 | Syntax error: 'import' and 'export' may only appear at the top level. (18:0) (18:undefined)
20:51:51.597 |  
20:51:51.597 |  
20:51:51.653 | error Command failed with exit code 1.
20:51:51.653 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:51:51.674 | Error: Command "yarn run build" exited with 1

**Pull request closed without merging**
