### PR TITLE
feat: ReDesigned login and Signup Page

### LINKED ISSUE #440: [Feature]: Redesign Login and Sign Up Pages for Enhanced User Experience
**Issue:** Redesign Login and Sign Up Pages for Enhanced User Experience

### Description:
This issue focuses on redesigning the login and sign up pages of the website to improve the user experience and provide a more intuitive and visually appealing interface for new and existing users. By revamping these key entry points, we aim to create a seamless and engaging onboarding process for users.

### Expected Outcome:

By redesigning the login and sign up pages, we aim to create a user-friendly and visually appealing experience that encourages new user registrations and facilitates easy access for existing users. This redesign will contribute to a positive first impression and establish a foundation for a seamless user journey throughout the website.

### Note: 

I would like to work under GSSoC'23
Please assign me this issue.

### PR DESCRIPTION
**Pull request by senthil-athiban**
closes #440 

ReDesigned the login and signup page as per given requirements in the issue 440

### CODE REVIEW

**Comment by senthil-k8s** [comment]
@sourabhsikarwar ?

**Comment by sourabhsikarwar** [comment]
Merge conflicts @senthil-k8s

**Comment by senthil-k8s** [comment]
@sourabhsikarwar conflict resolved

**Comment by senthil-k8s** [comment]
@sourabhsikarwar conflict resolved and everything working perfectly. need to review for deployment

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Failed in deployment

**Comment by senthil-k8s** [comment]
@sourabhsikarwar could u please log the error at which point, the deployment is failed

**Comment by sourabhsikarwar** [comment]
Hey, Just try to get a pull from master and then commit it back. I'll try to deploy it again.

**Pull request closed without merging**
