### PR TITLE
Fixed Issues #338 and #295

### PR DESCRIPTION
**Pull request by Harshu467**
## Related Issue
Not Proper View For User
Closes: #338 and #295 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots Before
Screenshot from 2023-06-26 19-04-20
Screenshot from 2023-06-26 19-04-16

Screenshot from 2023-06-26 19-04-01
Screenshot from 2023-06-26 19-04-04

## Screenshots After

Screenshot from 2023-06-26 19-02-12

Screenshot from 2023-06-26 19-02-22

Screenshot from 2023-06-26 19-02-34

Screenshot from 2023-06-26 19-02-39

### CODE REVIEW

**Comment by Harshu467** [comment]
@sourabhsikarwar  I have updated please do check and merge

**Comment by Harshu467** [comment]
Every time code I am facing conflicts , please look and try to merge as soon as possible @sourabhsikarwar

**Comment by Harshu467** [comment]
@sourabhsikarwar , Fixed Conflicts , please check and merge

**Comment by Harshu467** [comment]
@sourabhsikarwar  Please merge this PR it has been 3 weeks

**Comment by sourabhsikarwar** [comment]
Bhai take a pull from the update code. I have been saying this on discord for a while. Your PR will cause a lot of changes in the project.
Kindly update it with latest code and share images for that. @Harshu467

**Comment by Harshu467** [comment]
> Bhai take a pull from the update code. I have been saying this on discord for a while. Your PR will cause a lot of changes in the project. Kindly update it with latest code and share images for that. @Harshu467

Bro  check out my commits I have taken pull

**Comment by Harshu467** [comment]
This issue and PR are pending since a month please check out @sourabhsikarwar

**Comment by Harshu467** [comment]
Its been toooo much time for this PR to be merged and review , Conflicts are coming because of addition or updating of part others are doing which I am also doing and their PRS are been merged and that why I am facing this issue , It is my humble request from maintainers and project owners please check out , humble REQUEST. I am closing this PR and creating again for betterment , Thank YOu, I have updated code as every time I took pull before checking

**Pull request closed without merging**
