### PR TITLE
[FEAT]: Profile Page ReDesigned

### LINKED ISSUE #441: [Feature]: Redesign User Profile Edit Section for Enhanced User Control and Customization
**Issue:** Redesign User Profile Edit Section for Enhanced User Control and Customization

### Description:
This issue focuses on redesigning the user profile edit section of the website to provide users with improved control and customization options for their profiles. By revamping this section, we aim to enhance the user experience, empower users to manage their profile information easily, and personalize their profiles according to their preferences.

### Expected Outcome:
By redesigning the user profile edit section, we aim to provide users with an intuitive, visually appealing, and customizable interface that empowers them to manage their profiles effectively.

### PR DESCRIPTION
**Pull request by senthil-athiban**
Closes #441 

Redesigned the profile page with some features, and needs to be add some pages for our website. as of now, profile page is designed as per requirements in the issue.

### CODE REVIEW

**Comment by senthil-k8s** [comment]
https://www.loom.com/share/85d7d754d6de4f70979748e2e5106001?sid=0d838129-53d9-4a1f-87b9-21251525efad

**Comment by sourabhsikarwar** [comment]
Merge Conflicts @senthil-k8s 
Is it designed according to the dark mode also?

**Comment by senthil-k8s** [comment]
Ok, I will check it out.

**Comment by senthil-k8s** [comment]
@sourabhsikarwar  conflict solved for both the issue #473 and issue #472

**Comment by senthil-k8s** [comment]
@sourabhsikarwar conflict resolved and everything working perfectly. need to review for deployment.

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Failed in Deployment 

src/components/Banner/MovieBanner.jsx
13:17:01.012 | Line 226:18:  'Splide' is not defined       react/jsx-no-undef
13:17:01.012 | Line 228:22:  'SplideSlide' is not defined  react/jsx-no-undef
13:17:01.012 | Line 229:24:  'Youtube' is not defined      react/jsx-no-undef
 the keywords to learn more about each error.

**Comment by senthil-k8s** [comment]
@sourabhsikarwar now review the code to deploy.

**Pull request closed without merging**
