### PR TITLE
added movies display in mobile view

### PR DESCRIPTION
**Pull request by anamika7153**
## Related Issue

Closes: #291 

### Before

https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/121d31dd-967d-4ded-b73c-4574cab389bb

### Updated

https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/19f1e337-28c3-4c1c-826a-50fb6a6507e0

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by anamika7153** [comment]
@sourabhsikarwar Hey, I have resolved the issue, now the movies pages are being displayed on the mobile when the user clicks on any genre in the navbar. 
Please review and merge :)

**Comment by anamika7153** [comment]
@sourabhsikarwar this fix is urgently needed as genres of movies-dropdown is not redirecting to the requested page on mobile device. This PR fixes this issue.

**Comment by sourabhsikarwar** [comment]
Hey, Can you just update the code by taking a pull with the latest code. and please attach some screenshot for review @anamika7153

**Comment by anamika7153** [comment]
> Hey, Can you just update the code by taking a pull with the latest code. and please attach some screenshot for review @anamika7153

sure :)

**Comment by anamika7153** [comment]
@sourabhsikarwar  I have attached videos above. Please have a look :)

**Comment by anamika7153** [comment]
@sourabhsikarwar  please review and merge

**Comment by anamika7153** [comment]
@sourabhsikarwar could you please checkout this PR

**Comment by sourabhsikarwar** [comment]
It has some merge conflicts @anamika7153

**Comment by anamika7153** [comment]
> It has some merge conflicts @anamika7153

resolving right away

**Pull request closed without merging**
