### PR TITLE
Fixed Search bar bug

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## Related Issue
- The search results in the search bar do not match the theme of the website.

Closes: #370 

## Description of Changes
- I have fixed this issue by adding the appropriate CSS.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Screenshot 2023-06-29 142552 | image |
| Screenshot 2023-06-29 142539 | image|

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by saikiranreddy201** [comment]
Hey @sourabhsikarwar, please review my pr :)

**Comment by sourabhsikarwar** [comment]
Merge conflicts @saikiranreddy201

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by saikiranreddy201** [comment]
Resolved! Now review it @sourabhsikarwar :)

**Comment by saikiranreddy201** [comment]
Hey @sourabhsikarwar, please checkout my pr!

**Pull request merged**
