### PR TITLE
fix: improper padding and margin values applied to nav bar for mobiles ⚒️ 👷🏻‍♂️  

### LINKED ISSUE #541: revamp: nav bar for mobile 🙅🏻 ❌
## Description
- The current design of nav bar consists of incorrect padding and margin values.
- Due to this problem the nav bar not looks good for Mobile Devices and causes more bugs.
- We need to revamp the measurements a little bit so that we could properly resolve all the bugs on Nav bar for Mobile Devices.

## Screenshot
|||
|:---:|:----:|
|**BEFORE**|image|
|**AFTER**|image|

### PR DESCRIPTION
**Pull request by 0xabdulkhaliq**
## Description of Changes
- Fixed the improper padding and margin values applied for Nav bar on Mobile devices.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
|before |after|

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@sourabhsikarwar your review is appreciated 🙌🏻

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Deployment is failing @0xabdulkhalid

**Comment by 0xabdulkhalid** [comment]
@sourabhsikarwar I don't know why it's failing

May be it's due to other people's merges, This PR only changes with styles that's it.

I only modified the Styles, I'm not touched any other part of code, this might happen due to any old PR merge where you didn't verified the codebase changes and merged it. So that it now creating conflicts for other's PRs

You can check the [Files changed](https://github.com/sourabhsikarwar/Scene-Movie-Platform/pull/559/files) section.

**Comment by sourabhsikarwar** [comment]
You can do one thing, Take a pull from master and then commit your changes back again. There might be some old code which might creating issue in your PRs.

**Pull request closed without merging**
