### PR TITLE
Enhance the footer (Issue #376)

### PR DESCRIPTION
**Pull request by abrehan2**
## Related Issue

Closes: #376 

## Description of Changes
Hello, I've successfully integrated an improved and adaptable footer that not only enhances the overall aesthetics but also effectively embodies the essence of the web application.

**Demonstration:**
image

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| image| image|

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by sourabhsikarwar** [comment]
Kindly add the mobile and tablet view images also @abrehan2

**Comment by abrehan2** [comment]
**Tablet:** 

image

**Mobile:**

image

Here you go. :)
**If possible, please consider it a level 3 issue as I changed the entire layout for the footer, did it responsive, and even removed the necessary bugs in this component**

**Comment by abrehan2** [comment]
Done.

**Comment by sourabhsikarwar** [comment]
In tablet view, the logo is bit bigger and looks odd. 
And in mobile view, the footer content will look good as center aligned I guess.
Please look into that @abrehan2

**Comment by abrehan2** [comment]
@sourabhsikarwar It doesn't as I have checked the responsiveness through inspecting the tablets. Don't worry! It's errorless. 😅

**Comment by abrehan2** [comment]
Please merge the issue, thank you. ✨

**Comment by abrehan2** [comment]
@sourabhsikarwar okay, I will do it.

**Comment by abrehan2** [comment]
Please check now: 

image

**Review by sourabhsikarwar — APPROVED** [review]

**Pull request merged**
