### PR TITLE
added Mobile view movies and tv shows display

### PR DESCRIPTION
**Pull request by anamika7153**
## Related Issue

Closes: #291 

### Before

https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/121d31dd-967d-4ded-b73c-4574cab389bb

### Updated

https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/bebeb1be-1b10-4e9a-8efc-6d21716af934

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by anamika7153** [comment]
@sourabhsikarwar i have made a new PR and attached recent working video, review :)

**Comment by sourabhsikarwar** [comment]
Hey, Why you added bg1.png in images? @anamika7153 it might cause issues

**Comment by anamika7153** [comment]
> Hey, Why you added bg1.png in images? @anamika7153 it might cause issues

Someone's PR had this img in the about page, for that i added that. I'll remove

**Comment by anamika7153** [comment]
> Hey, Why you added bg1.png in images? @anamika7153 it might cause issues

@sourabhsikarwar deleted it

**Comment by anamika7153** [comment]
> Hey, Why you added bg1.png in images? @anamika7153 it might cause issues
Hey @sourabhsikarwar could you please review it again

**Review by sourabhsikarwar — APPROVED** [review]

**Pull request merged**
