### PR TITLE
Added key prop

### PR DESCRIPTION
**Pull request by Avinash905**
## Related Issue

Closes: #189 

## Description of Changes

Added key prop to all map functions which removed the error messages in the browser console.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
Check once for conflicts @Avinash905

**Comment by Avinash905** [comment]
> Check once for conflicts @Avinash905

Ok sure

**Comment by Avinash905** [comment]
I have created a new pr to resolve the conflicts https://github.com/sourabhsikarwar/Scene-Movie-Platform/pull/202

> Check once for conflicts @Avinash905

**Comment by Avinash905** [comment]
@sourabhsikarwar I have resolved the merge conflicts

**Pull request merged**
