### PR TITLE
popular genre cards ui

### PR DESCRIPTION
**Pull request by anamika7153**
## Related Issue

Closes: #418 

## Description of Changes
- Changed UI of popular genre cards to match UI of other cards.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
|image | image |
| image | <image |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by sourabhsikarwar** [comment]
The previous card looks good and different for genre! The current changes are not differentiable @anamika7153

**Comment by anamika7153** [comment]
> The previous card looks good and different for genre! The current changes are not differentiable @anamika7153

It was differential but it wasn't looking good, are there any changes you want in this one? like increasing the font size to highlight it?

**Comment by sourabhsikarwar** [comment]
You can change the design little fix @anamika7153

**Comment by anamika7153** [comment]
> You can change the design little fix @anamika7153

Do you have anything in mind?

**Comment by anamika7153** [comment]
@sourabhsikarwar I Have made few changes, updated the screenshots. You can check there. I think now it matches with other cards and is distinguishable too. What do you think?

**Review by sourabhsikarwar — APPROVED** [review]

**Pull request merged**
