### PR TITLE
heart button functionality added on the movie cards displayed on home page

### PR DESCRIPTION
**Pull request by shravan-das**
## Related Issue

Closes: #150 
(please npm i in root directory to add some packages(react-icon))

## Description of Changes

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

Screenshot (99)
Screenshot (100)
Screenshot (101)
 |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by sourabhsikarwar** [comment]
Changes are appreciable! Just check once again for merge conflicts! @shravan-das

**Comment by shravan-das** [comment]
> Changes are appreciable! Just check once again for merge conflicts! @shravan-das 
yes reviewing..

**Review by sourabhsikarwar — APPROVED** [review]

**Review by sourabhsikarwar — APPROVED** [review]

**Comment by sourabhsikarwar** [comment]
You can go through the cross button feature as it will help in better user experience! @shravan-das

**Comment by shravan-das** [comment]
For sure👍🏻

**Comment by shravan-das** [comment]
@sourabhsikarwar delete the users from database who have created there account before this pull request because....
function signUp(email, password) {
    createUserWithEmailAndPassword(auth, email, password);
    setDoc(doc(database, 'users', email), {
      savedShows: []
      
  })
  in this code above i have added savedShows[] array when user creates a account... previously it was only function signUp(email, password) {
     return createUserWithEmailAndPassword(auth, email, password);
  })
  
  so i would suggest you to delete the email or remove them from the database as they wouldnt able to access the like functionality

**Comment by sourabhsikarwar** [comment]
> @sourabhsikarwar delete the users from database who have created there account before this pull request because....
> 
> in authContext.js ->
> 
> function signUp(email, password) { createUserWithEmailAndPassword(auth, email, password); setDoc(doc(database, 'users', email), { savedShows: []
> 
> }) in this code above i have added savedShows[] array when user creates a account... previously it was only function signUp(email, password) { return createUserWithEmailAndPassword(auth, email, password); })
> 
> so i would suggest you to delete the email or remove them from the database as they wouldnt able to access the like functionality

Sure, will try to do something for this issue.
But, while checking this functionality and going to the fav. page, the screen got blank as it is having some issue/bug. Kindly, go through this. @shravan-das

**Comment by shravan-das** [comment]
it is showing blank because of the same reason i stated above 
only solution for this problem is delete all old users because a reference array  gets associated each time a new user signs up (array where fav shows gets stored)..which was not created before this pull request..

for now create a account and login with that account it will work fine thereafter

**Comment by sourabhsikarwar** [comment]
> it is showing blank because of the same reason i stated above only solution for this problem is delete all old users because a reference array gets associated each time a new user signs up (array where fav shows gets stored)..which was not created before this pull request..
> 
> for now create a account and login with that account it will work fine thereafter

Actually, I tested this with a new account only. then also it is showing the screen of death. @shravan-das

**Comment by shravan-das** [comment]
i have figured it out @sourabhsikarwar ... till 11 pm today i will give you a new pull request
t

**Comment by shravan-das** [comment]
i have fixed the issue which you stated above(showing dead for new accounts)
please accept my pull request :)

**Comment by shravan-das** [comment]
gave you the pull request bro and explained every possible detail/bugs and why the problem was occuring
and gave detailed steps
please give a thorough read of my PR #169 

peace!

**Pull request merged**
